config/routes.rb
W1bbs::Application.routes.draw do
  root :to => 'forums#index'

  match '/auth/:provider/callback' => 'sessions#login'
  match '/logout' => 'sessions#logout', :as => :logout

  match '/forums/:id/:filter' => 'forums#show', :constraints => {:filter => /(l\d+)|((\d+)?-?(\d+)?)/}

  resources :forums, :only => [:show, :new, :create] do
    resources :messages, :only => [:new, :create]
  end

end

app/models/forum.rb
class Forum < ActiveRecord::Base
  attr_accessible :title
  has_many :messages
  validates :title, :presence => true, :length => {:maximum => 64}
end

app/models/message.rb
require 'uri'

class Message < ActiveRecord::Base
  belongs_to :forum
  attr_accessible :body, :name, :position, :email
  validates :body, :presence => true, :length => {:maximum => 1024}, :lines_limit => true
  validates :email, :email => true, :length => {:maximum => 50}
  validates :name, :length => {:maximum => 50}
  validates :forum, :message_limit => true
  before_validation :position, :on => :create do
    if self.forum && last_message = self.forum.messages.last
      self.position = last_message.position + 1
    else
      self.position = 1
    end
  end
  before_validation :name, :on => :create do
    return unless self.name.is_a?(String)
    self.name = self.name[0, 50] if self.name.length > 50
  end
  before_save do
    self.forum.touch unless self.email == 'sage'
  end

  def self.filtered(forum, filter)
    case filter
    when /^l([0-9]+)$/
      o = forum.messages.length - $1.to_i
      o = 0 if o < 0
      where('position = 1 OR position > ?', o).order(:position)
    when /^([0-9]+)?-([0-9]+)?$/
      s = $1.to_i
      s = 0 unless s
      e = $2.to_i
      e = 1000 if !e or e < s
      where('position = 1 OR (position >= ? AND position <= ?)', s, e).order(:position)
    when /^([0-9]+)$/
      where(:position => $1.to_i)
    else
      order(:position)
    end
  end

  def body_html
    Rails.cache.fetch("body_html_#{self.id}") do
      body = CGI::escapeHTML(self.body)
      body.gsub!(/\n/, '<br />')
      URI.extract(body, ['http', 'https']).each do |url|
        raw_url = CGI::unescapeHTML(url)
        body.gsub!(url, "<a href='#{URI.escape(raw_url, /[^-_.!~*()a-zA-Z\d;\/?:@&=+$,\[\]%]/n)}' target='_blank'>#{url}</a>") # Escape include single quote and no escape percent
      end
      body.gsub!(/&gt;&gt;([0-9]+)?(-([0-9]+))?/) do
        "<a href='/forums/#{self.forum.id}/#{$1}#{$2}'>#{$&}</a>"
      end
      body
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  def index
    @forums = Forum.order('updated_at DESC')
    @message = Message.new
  end

  def new
    @forum = Forum.new
    @message = Message.new
  end

  def create
    @forum = Forum.new(params[:forum])
    @message = @forum.messages.build(params[:message])
    @message.name = session[:nickname]
    if @forum.save
      redirect_to @forum
    else
      render 'new'
    end
  end

  def show
    @forum = Forum.find(params[:id])
    @messages = @forum.messages.filtered(@forum, params[:filter])
    @message = Message.new
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  respond_to :html, :json

  def create
    @forum = Forum.find(params[:forum_id])
    @message = @forum.messages.build(params[:message])
    @message.name = session[:nickname]
    if @message.save
      from = params[:from_position].to_i
      messages = @forum.messages.where('position > ?', from).order(:position)
      respond_with do |format|
        format.html do
          if request.xhr?
            render :json => {:html => render_to_string(messages), :last_position => @message.position}
          else
            redirect_to "/forums/#{@forum.id}/#{@message.position}-"
          end
        end
      end
    else
      respond_with do |format|
        format.html do
          if request.xhr?
            render :json => @message.errors, :status => :unprocessable_entity
          else
            render
          end
        end
      end
    end
  end
end

app/controllers/sessions_controller.rb
# -*- coding: utf-8 -*-

class SessionsController < ApplicationController
  def login
    auth = request.env['omniauth.auth']

    session[:nickname] = auth[:info][:nickname]
    logger.debug auth.to_yaml
    redirect_to root_url, :notice => 'ログインしました。'
  end

  def logout
    session[:nickname] = nil
    redirect_to root_url, :notice => 'ログアウトしました。'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    return unless session[:nickname]

    @current_user = {
      :nickname => session[:nickname],
    }
  end
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/forums/_navigation.html.haml
.forum-nav
  - unless top
    = link_to '掲示板に戻る', root_path
    = link_to '新着', "/forums/#{forum.id}/#{forum.messages.length}-"
  = link_to '全部', forum_path(forum)
  = link_to '最新50件', "/forums/#{forum.id}/l50"

app/views/forums/_post_message_form.html.haml
- if forum.messages.length < 1000
  = form_for [forum, message], :remote => true do |f|
    .validation-error
    = hidden_field_tag :from_position, forum.messages.order(:position).last.position
    .submit
      = f.submit '書き込む'
    .name
      = f.label :name
      %span.name
        = session[:nickname] || '名無しさん'
    .email
      = f.label :email, 'E-mail(省略可)'
      = f.text_field :email
    .body
      = f.text_area :body
- else
  %p
    = 'このフォーラムは書き込み上限に達しました。'

app/views/forums/index.html.haml
%h1.title
  W1bbs

.description
  %p
    適当に作られた掲示板です。

.index
  - @forums.each_with_index do |forum, i|
    = link_to "#{i + 1}:#{forum.title}(#{forum.messages.length})", forum 

%div
  - @forums.each do |forum|
    %div.forum
      %h2
        = forum.title
      %dl
        = render forum.messages.filtered(forum, 'l10')
      = render :partial => 'post_message_form', :locals => {:forum => forum, :message => @message}
      = render :partial => 'navigation', :locals => {:forum => forum, :top => true}

.footer
  = link_to '新規フォーラム作成画面へ', new_forum_path

app/views/forums/new.html.haml
- content_for :title do
  フォーラムの新規作成
%h1.title
  フォーラムの新規作成
.forum
  %ul
    - @forum.errors.full_messages.each do |msg|
      %li
        = msg
  = form_for @forum do |f|
    %div
      = f.label :title
      = f.text_field :title
      = f.submit '新規フォーラム作成'
    = fields_for @message do |f|
      .name
        = f.label :name
        %span.name
          = session[:nickname] || '名無しさん'
      .email
        = f.label :email, 'E-mail(省略可)'
        = f.text_field :email
      .body
        = f.text_area :body
  %p
    = link_to '掲示板に戻る', root_path

app/views/forums/show.html.haml
- content_for :title do
  = @forum.title
.forum{:id => ['forum', @forum.id]}
  = render :partial => 'navigation', :locals => {:forum => @forum, :top => false}
  %h1
    = @forum.title

  %dl
    = render @messages

  = render :partial => 'post_message_form', :locals => {:forum => @forum, :message => @message}
  = render :partial => 'navigation', :locals => {:forum => @forum, :top => false}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      = content_for?(:title) ? yield(:title) + ' - W1bbs' : 'W1bbs'
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{:name => 'viewport', :content => 'width=device-width'}
  %body
    .header
      - if current_user
        = "Hello, #{current_user[:nickname]}."
        = link_to 'ログアウト', logout_path
      - else
        = link_to 'Facebookでログインする', '/auth/facebook'
    .main
      = yield

app/views/messages/_message.html.haml
%dt
  = "#{message.position}:"
  - if message.email.blank?
    %span.name
      = ( message.name.blank? ? '名無しさん' : message.name )
  - else
    %span.email
      = mail_to(message.email, ( message.name.blank? ? '名無しさん' : message.name ) )
  - unless message.name.blank?
    %span.facebook-wall
      %a{:href => "http://www.facebook.com/#{message.name}"} facebook
  = message.created_at.strftime("%Y年%m月%d日 %H:%M")
%dd
  = raw message.body_html
  %br
  %br

app/views/messages/create.html.haml
%h1 メッセージの書き込み
.forum
  %ul
    - @message.errors.full_messages.each do |msg|
      %li
        = msg
  = link_to '戻る', @forum

app/views/messages/new.html.haml
%h1 Messages#new
%p Find me in app/views/messages/new.html.haml